// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7sDjVDwNv6DRJtp_EnkghwpkQCDlGUXE',
    appId: '1:47358986697:web:564cc152a52d637606c018',
    messagingSenderId: '47358986697',
    projectId: 'signin-example-2486f',
    authDomain: 'signin-example-2486f.firebaseapp.com',
    databaseURL: 'https://signin-example-2486f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'signin-example-2486f.appspot.com',
    measurementId: 'G-3K8E2DMNSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCduNoZM0YjJvL9nex26m_ouqHjKpl_Vgg',
    appId: '1:47358986697:android:28edcef23c951ffb06c018',
    messagingSenderId: '47358986697',
    projectId: 'signin-example-2486f',
    databaseURL: 'https://signin-example-2486f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'signin-example-2486f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKM47kxSyrCoHM6jA-MNQ2DM3KPNCJpc',
    appId: '1:47358986697:ios:6146a5575e6b168f06c018',
    messagingSenderId: '47358986697',
    projectId: 'signin-example-2486f',
    databaseURL: 'https://signin-example-2486f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'signin-example-2486f.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKM47kxSyrCoHM6jA-MNQ2DM3KPNCJpc',
    appId: '1:47358986697:ios:ebb1ec8dd6eccb2706c018',
    messagingSenderId: '47358986697',
    projectId: 'signin-example-2486f',
    databaseURL: 'https://signin-example-2486f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'signin-example-2486f.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
